language: python
dist: focal
python:
   - "3.8"
install:
   #  APT stuff is below separately
   - pip install codecov wenv
   - pip install -r requirements.txt
   # - python setup.py install # no need to install mupif really
   # wenv
   - echo '{"arch":"win64"}' > ~/.wenv.json
   - wenv init
   - wenv pip install --only-binary=pyrsistent -r requirements.txt

script:
   - ls -l
   - pwd
   - nosetests --rednose -v --with-coverage
   - codecov -F unittests
   - pwd
   - pushd mupif/examples
   - USE_CODECOV=true /bin/bash testExamples.sh
   - popd
   - codecov -F examples
   # test under wine
   - wenv nosetests --rednose
   - cd examples; USE_WENV=true /bin/bash testExamples.sh

sudo: false
addons:
   apt:
      packages:
         - python3-pip
         - openssh-server
         - openssh-client
         - wine64
         - wine
