os: linux
dist: focal
language: python
python:
   - "3.8"
install:
   #  APT stuff is below separately
   - pip install codecov wenv
   - pip install -r requirements.txt
   # no need to install mupif really
   # - python setup.py install 
   # prepare windows (wenv)
   - echo '{"arch":"win64"}' > ~/.wenv.json
   - wenv init
   - wenv pip install --only-binary=pyrsistent -r requirements.txt

script:
   : run tests and examples under Linux, reporting coverage
   - nosetests --rednose -v --with-coverage
   - codecov -F unittests
   - cd examples; USE_CODECOV=true /bin/bash testExamples.sh
   - codecov -F examples
   # run tests and examples under wine (via wenv)
   - echo '####################################################################################'
   - echo '########### WINDOWS ################################################################'
   - wenv nosetests --rednose
   - cd examples; USE_WENV=true /bin/bash testExamples.sh

addons:
   apt:
      packages:
         - python3-pip
         - openssh-server
         - openssh-client
         - wine64
         - wine
