# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MuPIF

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test-linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]
        # fail-fast: 0
      # max-parallel: 1 # avoid localhost conflicts
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install python3-wheel python3-pip dos2unix
        python -m pip install -q codecov flake8
        pip install -q -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=obsolete
        # this is too verbose and is mostly just coding style
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=obsolete
    - name: nosetests (native)
      timeout-minutes: 1
      run: |
        set -euo pipefail
        nosetests --rednose --force-color -v --with-coverage 2>&1 | tools/grcat-mupif
        codecov -F unittests
    - name: examples (native)
      timeout-minutes: 2 # normally about 35s
      run: |
        set -euo pipefail
        cd examples; ./runex.py --codecov 2>&1 | ../tools/grcat-mupif

  test-wine64:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install wine64 wine python3-pip dos2unix
        python -m pip install wenv
        echo '{"arch":"win64","pythonversion":"3.8.5"}' > ~/.wenv.json
        wenv init
        wenv pip install --only-binary=pyrsistent -r requirements.txt
    - name: nosetests
      timeout-minutes: 1
      run: |
        set -euo pipefail
        wenv python -m nose -v --rednose --traverse-namespace 2>&1 | dos2unix | tools/grcat-mupif
    - name: examples
      timeout-minutes: 2 # normally about 50s
      run: |
        set -euo pipefail
        # skip test 7, somehow fails under wine
        cd examples; wenv python runex.py --wenv=all 1 2 3 4 5 6 8 2>&1 | dos2unix | ../tools/grcat-mupif

  test-docker-VPN:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    # this should somehow enable persistent docker layer cache
    # so that we don't have to build the full image from scratch (ubuntu:20.04)
    # every time
    # see https://github.com/marketplace/actions/docker-layer-caching
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Distributed example on Docker containers in VPN
      run:
        make -C tools/vpn/wireguard default

  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8] # , 3.9]
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install wheel
        python3 -m pip install -r requirements.txt
    - name: nosetests
      timeout-minutes: 1
      # --traverse-namespace necessary for windows, see https://github.com/Pyomo/pyomo/issues/1257
      run: python3 -m nose -v --rednose --traverse-namespace
      # 2>&1 | python3 -u tools/grcat-mupif
    - name: examples
      timeout-minutes: 2
      run: python3 examples/runex.py
      # 2>&1 | python3 -u ../tools/grcat-mupif


