# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MuPIF

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ 3.8 ]  # , 3.9
        # runs-on: [ubuntu-20.40, windows-2019]
        # fail-fast: 0
      max-parallel: 1 # avoid localhost conflicts
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install grc openssh-server wine64 wine flake8 python3-wheel python3-pip
        # python -m pip install --upgrade pip
        python -m pip install -q codecov wenv
        pip install -q -r requirements.txt
    - name: Prepare wenv
      run: |
        echo '{"arch":"win64"}' > ~/.wenv.json
        wenv init
        wenv pip install -q --only-binary=pyrsistent -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=obsolete
        # this is too verbose and is mostly just coding style
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=obsolete
    - name: nosetests (native)
      run: |
        nosetests --rednose --force-color -v --with-coverage
        codecov -F unittests
    - name: nosetests (win64)
      run: |
        wenv nosetests --rednose --force-color -v
    - name: examples (native)
      run: |
        #  grc --config grc.conf --stdout --stderr 
        cd examples; USE_CODECOV=true bash ./testExamples.sh 2>&1 | grcat grc.conf 
        # codecov -F examples
    - name: exmaples (win32)
      run: |
        cd examples; USE_WENV=true bash ./testExamples.sh 2>&1 | grcat grc.conf
